### ISSUE TITLE
Contribute with a Commerce Merchant Toolkit app built with Retool on top of the Sitecore Order Cloud APIs

### ISSUE THREAD

**Issue by medkrimi** [tryretool/retool-app-exchange#44]
[Sitecore Commerce Order Cloud ](https://www.sitecore.com/products/ordercloud) provides organizations with a highly flexible, scalable way to manage their product or services. With its composable, API-first and cloud native proven architecture, developers and business users can improve prototyping and quickly build and deliver Commerce experiences with less-risk and high innovation.

I am Mohamed Krimi Solutions Architect at Sitecore, I have been working the last month on building an easy, simple UI to be able to showcase the Order Cloud APIs capabilities. 

So, I am building a Merchant Toolkit Retool App to allow any commerce user to connect to the Order Cloud instance of his choice and be able to manage : 
- Marketplace Buyers, Sellers, Suppliers and Users
- Commerce Catalogs and Categories
- Products and Prices Schedules
- Promotions. 

The app code will remain under an MIT license and is not related to Sitecore, and will not be supported by Sitecore. It is a personal contribution to the open source community to showcase how they can build business internal applications for their B2B commerce team using Sitecore Order Cloud + Retool.

**Comment by evanRetool** [comment]
Hi Mohamed, this seems like a great idea! I'll follow up with you via email to confirm a few details.
