### ISSUE TITLE
Integrate with notion instead of postgres?

### ISSUE THREAD

**Issue by shreyanshp** [tryretool/retool-app-exchange#7]
Just curious if it would make more sense to integrate with notion.so?

**Comment by evanRetool** [comment]
Hi @shreyanshp , apologies for the delay in getting back to you on this!

It should absolutely be possible to build Retool apps which integrate with [Notion's REST API](https://developers.notion.com/). You would use the [Retool REST API Resource](https://docs.retool.com/docs/connect-api-resource) to make queries against Notion databases.

This would work a bit differently from databases like Postgres which suppose SQL queries, but you could likely get what you want. Do you think this would work? We'd love to hear more about your use-case for integrating with Notion!

**Comment by evanRetool** [comment]
Hi @shreyanshp, I'm going to close this issue out for now. Please let me know if you'd like to chat more about how to use Retool with Notion!
